---
version: '3'

services:
  puppet:
    hostname: puppet
    image: puppet/puppetserver
    environment:
      - 'TESTING=1'
      - 'DNS_ALT_NAMES=puppet'
      # This variable originally comes from
      # https://github.com/puppetlabs/puppetserver/blob/master/docker/puppetserver-standalone/Dockerfile
      - 'PUPPETSERVER_JAVA_ARGS=-Xms1g -Xmx1g -XX:+HeapDumpOnOutOfMemoryError'
      - PUPPET_STORECONFIGS_BACKEND
      - PUPPET_STORECONFIGS
      - PUPPET_REPORTS
      - CONSUL_ENABLED
    links:
      - puppetdb
    ports:
      - 8140:8140
    volumes:
      - ./environments/production:/etc/puppetlabs/code/environments/production:ro
      - ./.docker/puppetserver/ssl:/etc/puppetlabs/puppet/ssl/
      - ./.docker/puppetserver/serverdata:/opt/puppetlabs/server/data/puppetserver/

  postgres:
    image: postgres:10
    environment:
      - POSTGRES_DB=puppetdb
      - POSTGRES_USER=puppetdb
      - POSTGRES_PASSWORD=puppetdb
    expose:
      - 5432
    volumes:
      - ./.docker/postgres/data:/var/lib/postgresql/data/
      - ./test/postgres/init/:/docker-entrypoint-initdb.d/

  puppetdb:
    hostname: puppetdb
    image: puppet/puppetdb
    ports:
      - 8080
      - 8081
    volumes:
      - ./.docker/puppetdb/ssl:/etc/puppetlabs/puppet/ssl/

  ubuntu:
    image: puppet/puppet-agent-ubuntu
    links:
      - puppet
